=== anhduc3820/XMl_1/menu.dtd
<?xml encoding="UTF-8"?>
<!ELEMENT Menu (food)>
<!ELEMENT food (name, price, description, calories)>
<!ATTLIST food type (Salad|Main Course|Desserts|Drinks) "Salad">
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT calories (#PCDATA)>

=== anhduc3820/XMl_1/menu.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<?xml-stylesheet type="text/xsl" href="menu.xsl" ?>
<!DOCTYPE DOCUMENT SYSTEM "menu.dtd">

<Menu>
    <food type="Desserts">
        <name>Chicken</name>
        <price>$200</price>
        <description>fried chicken</description>
        <calories>400</calories>
    </food>
    <food type="Salad">
        <name>Strawberry Belgian Waffles</name>
        <price>$7.95</price>
        <description>Light Belgian waffles covered with strawberries and whipped cream</description>
        <calories>200</calories>
    </food>
    <food type="Main Course">
        <name>Beef</name>
        <price>$300</price>
        <description>Beef fried with melon</description>
        <calories>600</calories>
    </food>
    <food type="Drinks">
        <name>Orange</name>
        <price>$7</price>
        <description>orange juice</description>
        <calories>150</calories>
    </food>
</Menu>
